services:
  # =====================
  # NGINX (ENTRYPOINT)
  # =====================
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx-dev
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/conf.d:ro
    depends_on:
      api-gateway:
        condition: service_started
      grafana:
        condition: service_started
    networks:
      - saas-dev

  # =====================
  # API GATEWAY
  # =====================
  api-gateway:
    container_name: api-gateway-dev
    build:
      context: ..
      dockerfile: services/api-gateway/Dockerfile.dev
    env_file:
      - ../services/api-gateway/.env
    volumes:
      - ..:/app
    networks:
      - saas-dev

  # =====================
  # AUTH SERVICE
  # =====================
  auth-service:
    container_name: auth-service-dev
    build:
      context: ..
      dockerfile: services/auth-service/Dockerfile.dev
    env_file:
      - ../services/auth-service/.env
    volumes:
      - ..:/app
    depends_on:
      - auth-postgres
      - redis
      - mongo
    networks:
      - saas-dev

  # =====================
  # POSTGRES (AUTH)
  # =====================
  auth-postgres:
    image: postgres:16-alpine
    container_name: auth-postgres-dev
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data
    networks:
      - saas-dev

  # =====================
  # REDIS
  # =====================
  redis:
    image: redis:7-alpine
    container_name: redis-dev
    ports:
      - "6379:6379"
    networks:
      - saas-dev

  # =====================
  # MONGO
  # =====================
  mongo:
    image: mongo:7
    container_name: mongo-dev
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - saas-dev

  # =====================
  # PROMETHEUS
  # =====================
  prometheus:
    image: prom/prometheus
    container_name: prometheus-dev
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - saas-dev

  # =====================
  # LOKI
  # =====================
  loki:
    image: grafana/loki:3.0.0
    container_name: loki-dev
    volumes:
      - ./loki/loki.yml:/etc/loki/loki.yml
    command: -config.file=/etc/loki/loki.yml
    networks:
      - saas-dev

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail-dev
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    depends_on:
      - loki
    networks:
      - saas-dev

  # =====================
  # MAILPIT
  # =====================
  mailpit:
    image: axllent/mailpit
    container_name: mailpit-dev
    ports:
      - "8025:8025"
    networks:
      - saas-dev

  # =====================
  # GRAFANA
  # =====================
  grafana:
    image: grafana/grafana
    container_name: grafana-dev
    ports:
      - "3005:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/provisioning/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus
      - loki
    networks:
      - saas-dev

  # =====================
  # PGADMIN
  # =====================
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - saas-dev

  # =====================
  # REDIS COMMANDER
  # =====================
  redis-commander:
    image: rediscommander/redis-commander
    platform: linux/amd64
    container_name: redis-commander-dev
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - saas-dev

  # =====================
  # MONGO EXPRESS
  # =====================
  mongo-express:
    image: mongo-express
    container_name: mongo-express-dev
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - "8082:8081"
    networks:
      - saas-dev


networks:
  saas-dev:
    driver: bridge

volumes:
  auth-postgres-data:
  mongo-data:
